# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/doxygen
image: python:alpine

pages:
  script:
    - apk update && apk add doxygen && apk add texlive && apk add ghostscript
    - doxygen src/plastimatch/Doxyfile
    - mkdir -p public
    - mv html/ public/doxygen
    - ls public/doxygen
    - pip install -U sphinx
    - sphinx-build -b html doc/sphinx public
  artifacts:
    paths:
      - public
  only:
    - master
