# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/doxygen
image: alpine

pages:
  script:
    - apk update && apk add doxygen && apk add texlive
    - doxygen src/plastimatch/Doxyfile
    - mkdir -p public/doxygen
    - mv html/ public/doxygen
    - ls public/doxygen
  artifacts:
    paths:
      - public
  only:
    - master
